apiVersion: v1
kind: Service
metadata:
  name: sudip-portfolio
spec:
  selector:
    app: sudip-portfolio
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocal: TCP
    selector:
      app: sudip-portfolio
    type: ClusterIP
